{{- if .Values.enduser.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "forgerock.enduser.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.enduser.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.enduser.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "forgerock.enduser.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: tcp-{{ lower .Values.enduser.container.protocol }}
      port: {{ .Values.enduser.container.port}}
      targetPort: {{ .Values.enduser.container.targetPort}}
{{- end -}}