{{- if and .Values.admin.enabled .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "forgerock.admin.fullname". }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: frim
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    cert-manager.io/cluster-issuer: "vault-issuer"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ upper .Values.admin.ingress.backend.protocol }}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
spec:
  {{- if .Values.admin.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- toYaml .Values.admin.ingress.hosts | nindent 4 }}
    secretName: {{ .Values.admin.ingress.tls.secretName | default (printf "%s-ingress-tls" (include "forgerock.fullname" .)) }}
  {{- end }}
  rules:
  {{- $root := . -}}
  {{- range .Values.admin.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "forgerock.admin.fullname" $root }}
            port:
              number: {{ $root.Values.admin.ingress.backend.port }}
  {{- end }}
  ingressClassName: nginx
{{- end }}