{{- if .Values.admin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "forgerock.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.admin.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "forgerock.admin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  ports:
    - name: tcp-{{ lower .Values.admin.container.protocol }}
      port: {{ .Values.admin.container.port}}
      targetPort: {{ .Values.admin.container.targetPort}}
{{- end -}}