{{ if ge .Values.directory.replicas 1.0  }}
{{- if or .Values.directory.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "forgerock.frds.ds.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.ds.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.directory.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.directory.serviceAccount.annotations }}
  annotations: 
  {{ toYaml .Values.directory.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.directory.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}