{{ if ge .Values.directory.replicas 1.0  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.frds.ds.fullname". }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.ds.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.directory.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.directory.configAnnotations }}
  annotations: {{ toYaml .Values.directory.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- if ne .Values.directory.instance.type "directory" }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.replication.bootstrap" . }}
  {{- else }}
  {{- if ge .Values.directory.replicas 1.0 }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.directory.bootstrap" . }}
  {{- end }}
  {{- end }}
  {{- with .Values.directory.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}