{{ if ge .Values.directory.replicas 1.0  }}
{{- if and .Values.rbac.create .Values.directory.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.frds.ds.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.ds.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.directory.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}