{{ if ge .Values.directory.replicas 1.0  }}
{{- if and .Values.rbac.create .Values.directory.rbac.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.frds.ds.fullname". }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.ds.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.directory.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.directory.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.directory.serviceAccount.annotations | indent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name:  {{ template "forgerock.frds.ds.fullname". }}
roleRef:
  kind: Role
  name: {{ template "forgerock.frds.ds.fullname". }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}