{{ if ge .Values.directory.replicas 1.0  }}
{{- if .Values.directory.proxy.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "forgerock.frds.ds.fullname". }}-schema
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.ds.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.directory.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.directory.persistentVolume.schema.storageClassName }}
  storageClassName: {{ .Values.directory.persistentVolume.schema.storageClassName }}
  {{- end }}
  capacity:
    storage: {{ .Values.directory.persistentVolume.schema.storageSize}}
  accessModes:
  - ReadWriteMany 
{{- end }}
{{- end }}