apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.fullname". }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.platform.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.platform.configAnnotations }}
  annotations: {{ toYaml .Values.platform.configAnnotations | nindent 4 }}
  {{- end }}
data:
  AM_URL: {{ .Values.platform.endpoint }}/am
  AM_ADMIN_URL: {{ .Values.platform.endpoint }}/am/ui-admin
  IDM_REST_URL: {{ .Values.platform.endpoint }}/openidm
  IDM_ADMIN_URL: {{ .Values.platform.endpoint }}/admin
  IDM_UPLOAD_URL: {{ .Values.platform.endpoint }}/upload
  IDM_EXPORT_URL: {{ .Values.platform.endpoint }}/export
  ENDUSER_UI_URL: {{ .Values.platform.endpoint }}/enduser-ui
  PLATFORM_ADMIN_URL: {{ .Values.platform.endpoint }}/platform-ui/
  ENDUSER_CLIENT_ID: end-user-ui
  ADMIN_CLIENT_ID: idm-admin-ui
  THEME: default
  PLATFORM_UI_LOCALE: en
  {{- if .Values.platform.env }}
  {{- with .Values.platform.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}