{{- if or .Values.platform.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "forgerock.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.platform.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.platform.serviceAccount.annotations }}
  annotations: 
  {{ toYaml .Values.platform.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.platform.serviceAccount.automountServiceAccountToken }}
{{- end }}