{{- if .Values.platform.rbac.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.platform.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name:  {{ template "forgerock.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "forgerock.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}