{{ if ge .Values.replication.replicas 1.0  }}
{{- if .Values.replication.proxy.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "forgerock.frds.rs.fullname". }}-schema
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.replication.persistentVolume.schema.storageClassName }}
  storageClassName: {{ .Values.replication.persistentVolume.schema.storageClassName }}
  {{- end }}
  capacity:
    storage: {{ .Values.replication.persistentVolume.schema.storageSize}}
  accessModes:
  - ReadWriteMany 
{{- end }}
{{- end }}