{{ if ge .Values.replication.replicas 1.0  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forgerock.frds.rs.fullname". }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  ROOT_USER_PASSWORD: {{ .Values.replication.secrets.directorymanager.password | b64enc }}
  MONITOR_USER_PASSWORD: {{ .Values.replication.secrets.monitor.password | b64enc }}
  DEPLOYMENT_KEY: {{ .Values.replication.secrets.deploymentkey.value | b64enc }}
  DEPLOYMENT_KEY_PASSWORD: {{ .Values.replication.secrets.deploymentkey.password | b64enc }}
  {{- if has .Values.replication.instance.type (list "amconfig" "development") }}
  AMCONFIG_ADMIN_PASSWORD: {{ .Values.replication.secrets.amconfig.password | b64enc }}
  {{- end }}
  {{- if has .Values.replication.instance.type (list "identity" "development") }}
  AMIDENTITYSTORE_ADMIN_PASSWORD: {{ .Values.replication.secrets.identity.password | b64enc }}
  {{- end }}
  {{- if has .Values.replication.instance.type (list "cts" "development") }}
  AMCTS_ADMIN_PASSWORD: {{ .Values.replication.secrets.cts.password | b64enc }}
  {{- end }}
  jksPassword: {{ .Values.replication.instance.keystore.password | b64enc }}
  {{- end }}