{{ if ge .Values.replication.replicas 1.0  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "forgerock.frds.rs.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "forgerock.rs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "forgerock.frds.rs.fullname". }}
  ports:
    - name: tcp-admin
      port: 4444
    - name: tcp-replication
      port: 8989 
{{- end }}