{{ if ge .Values.replication.replicas 1.0  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.frds.rs.fullname". }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.replication.configAnnotations }}
  annotations: {{ toYaml .Values.replication.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- if ne .Values.replication.instance.type "directory" }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.replication.bootstrap" . }}
  {{- else }}
  {{- if ge .Values.replication.replicas 1.0 }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.directory.bootstrap" . }}
  {{- end }}
  {{- end }}
  {{- with .Values.replication.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}