
{{ if ge .Values.replication.replicas 1.0  }}
{{- if .Values.replication.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.frds.rs.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}