{{ if ge .Values.replication.replicas 1.0  }}
{{- if and (.Values.replication.rbac.enabled) (.Values.replication.useKeystore) -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.rs.serviceAccountName" . }}-genjks-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.rs.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.replication.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-10"
  {{- if .Values.replication.serviceAccount.annotations }}
    {{ toYaml .Values.replication.serviceAccount.annotations | indent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name:  {{ template "forgerock.rs.serviceAccountName" . }}-genjks
roleRef:
  kind: Role
  name: {{ template "forgerock.rs.serviceAccountName" . }}-genjks-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}