---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}-role
  {{- if .Values.annotations }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}-role-binding
  {{- if .Values.annotations }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}
subjects:
- kind: ServiceAccount
  name:  {{ template "forgerock.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "forgerock.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}
  {{- if .Values.annotations }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}