{{- if and (.Values.fram.rbac.enabled) (.Values.fram.useKeystore) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: fram
    {{- with .Values.fram.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.fram.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.fram.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.fram.automountServiceAccountToken }}
{{- end }}