apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forgerock.fullname". }}-init-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: fram
    {{- with .Values.fram.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  FRAM_ADMIN_PASSWORD: {{ .Values.fram.secrets.admin.password | b64enc }}
  FRAM_CFG_STORE_DIR_MGR_PWD: {{ .Values.fram.secrets.cfgStore.password | b64enc }}
  FRAM_USER_STORE_DIR_MGR_PWD: {{ .Values.fram.secrets.userStore.password | b64enc }}
  FRAM_CTS_STORE_DIR_MGR_PWD: {{ .Values.fram.secrets.ctsStore.password | b64enc }}