apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "forgerock.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: fram
    {{- with .Values.fram.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podManagementPolicy: Parallel 
  selector:
    matchLabels:
      {{- include "forgerock.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fram
  {{- if not .Values.fram.autoscaling.enabled }}
  replicas: {{ .Values.fram.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.fram.revisionHistoryLimit }}
  {{- if .Values.fram.updateStrategy }}
  strategy:
    {{ toYaml .Values.fram.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.fram.minReadySeconds }}
  serviceName: {{ template "forgerock.fullname". }}
  template:
    metadata:
      labels:
        {{- include "forgerock.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fram
        {{- with .Values.fram.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.fram.podLabels }}
        {{- toYaml .Values.fram.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fram-configmap-fram.yaml") . | sha256sum }}
       {{- if .Values.fram.podAnnotations }}
      {{- range $key, $value := .Values.fram.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      {{- if .Values.fram.dnsConfig }}
      dnsConfig: {{ toYaml .Values.fram.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.hostname }}
      hostname: {{ toYaml .Values.fram.hostname | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.fram.dnsPolicy }}
      {{- if .Values.fram.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.fram.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.priorityClassName }}
      priorityClassName: {{ .Values.fram.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.fram.hostNetwork }}
      hostNetwork: {{ .Values.fram.hostNetwork }}
      {{- end }}
      {{- if .Values.fram.nodeSelector }}
      nodeSelector: {{ toYaml .Values.fram.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.tolerations }}
      tolerations: {{ toYaml .Values.fram.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.affinity }}
      affinity: {{ toYaml .Values.fram.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.fram.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if or .Values.fram.podSecurityContext .Values.fram.sysctls }}
      securityContext:
      {{- end }}
      {{- if .Values.fram.podSecurityContext }}
        {{- toYaml .Values.fram.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.fram.sysctls }}
        sysctls:
      {{- range $sysctl, $value := .Values.fram.sysctls }}
        - name: {{ $sysctl | quote }}
          value: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.fram.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.fram.shareProcessNamespace }}
      {{- end }}
      serviceAccountName: {{ template "forgerock.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.fram.terminationGracePeriodSeconds }}
      initContainers:
        {{- if .Values.fram.services }}
        - name: wait-for-first
          image: opsfleet/depends-on
          imagePullPolicy: {{ .Values.fram.image.imagePullPolicy }}
          {{ template "forgerock.waitfor". }}
        {{- end }}
        - name: init
          image: {{ .Values.fram.image.repository }}:{{ .Values.fram.image.tag }}
          imagePullPolicy: {{ .Values.fram.image.imagePullPolicy }}
          envFrom:
          - secretRef:
              name: {{ template "forgerock.fullname". }}-init-secrets
          - configMapRef:
              name: {{ template "forgerock.fullname". }}-init-config
          command:
            - ./docker-entrypoint.sh
            - init
          volumeMounts:
            - mountPath: /opt/fram/instance/data
              name: {{ template "forgerock.fullname". }}-data-volume
            {{- if .Values.fram.useKeystore }}
            - mountPath: /var/run/secrets/fram
              name:  {{ template "forgerock.fullname". }}-keystore
              readOnly: true  
            {{- end }}
      containers:
      - name: fram
        image: {{ .Values.fram.image.repository }}:{{ .Values.fram.image.tag }}
        imagePullPolicy: {{ .Values.fram.image.imagePullPolicy }}
        {{- if .Values.fram.lifecycle }}
        lifecycle: {{ toYaml .Values.fram.lifecycle | nindent 12 }}
        {{- end }}
        securityContext: {{ include "fram.containerSecurityContext" . | nindent 12 }}
        envFrom:
        - secretRef:
            name: {{ template "forgerock.fullname". }}-secrets
        - configMapRef:
            name: {{ template "forgerock.fullname". }}-config 
        ports:
        - containerPort: {{ .Values.fram.ingress.backend.port}}
        volumeMounts:
          - mountPath: /opt/fram/instance/data
            name: {{ template "forgerock.fullname". }}-data-volume
          {{- if .Values.fram.useKeystore }}
          - mountPath: /var/run/secrets/fram
            name:  {{ template "forgerock.fullname". }}-keystore
            readOnly: true
          {{- end }}
        {{- if .Values.fram.startupProbe }}  
        startupProbe: {{ toYaml .Values.fram.startupProbe | nindent 12 }}
        {{- end }}
        livenessProbe: {{ toYaml .Values.fram.livenessProbe | nindent 12 }}
        readinessProbe: {{ toYaml .Values.fram.readinessProbe | nindent 12 }}
        {{- if .Values.fram.resources }}
        resources: {{ toYaml .Values.fram.resources | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.fram.useKeystore }}
        - name:  {{ template "forgerock.fullname". }}-keystore
          secret:
            secretName:  {{ template "forgerock.fullname". }}-keystore
            items:
            - key: keystore.jks
              path: keystores/keystore.jks
            - key: keystore.jceks
              path: keystores/keystore.jceks
            - key: keystore.entrypass
              path: secrets/plain/entrypass
            - key: keystore.storepass
              path: secrets/plain/storepass
            - key: truststore.jks
              path: keystores/truststore.jks
            - key: truststore.storepass
              path: secrets/plain/truststore.storepass
            - key: tls.key
              path: tls.key
            - key: tls.crt
              path: tls.crt
            - key: ca.crt
              path: ca.crt
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "forgerock.fullname". }}-data-volume
    spec:
      {{- if .Values.fram.volumeClaimTemplates.data.storageClassName }}
      storageClassName: {{ .Values.fram.volumeClaimTemplates.data.storageClassName }}
      {{- end }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.fram.volumeClaimTemplates.data.storageSize }}