apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.fullname". }}-init-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: fram
    {{- with .Values.fram.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.fram.configAnnotations }}
  annotations: {{ toYaml .Values.fram.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.fram.stores.cfgStore.enabled }}
  FRAM_CFG_STORE_DIR_MGR: {{ .Values.fram.secrets.cfgStore.uid }}
  FRAM_CFG_STORE_HOST: {{ template "forgerock.framHost" (list "amconfig" .) }}
  FRAM_CFG_STORE_PORT: {{ template "forgerock.framPort" (list "amconfig" .) }}
  FRAM_CFG_STORE_SSL: {{ template "forgerock.framSSL" (list "amconfig" .) }}
  FRAM_CFG_STORE_ROOT_SUFFIX: {{ .Values.fram.stores.cfgStore.rootSuffix }}
  {{- end }}
  {{- if .Values.fram.stores.cfgStore.enabled }}
  FRAM_USER_STORE_DIR_MGR: {{ .Values.fram.secrets.userStore.uid }}
  FRAM_USER_STORE_HOST: {{ template "forgerock.framHost" (list "identity" .) }}
  FRAM_USER_STORE_PORT: {{ template "forgerock.framPort" (list "identity" .) }}
  FRAM_USER_STORE_SSL: {{ template "forgerock.framSSL" (list "identity" .) }}
  FRAM_USER_STORE_ROOT_SUFFIX: {{ .Values.fram.stores.userStore.rootSuffix }}
  {{- end }}
  {{- if .Values.fram.stores.ctsStore.enabled }}
  FRAM_CTS_STORE_DIR_MGR: {{ .Values.fram.secrets.ctsStore.uid }}
  FRAM_CTS_STORE_HOST: {{ template "forgerock.framHost" (list "cts" .) }}
  FRAM_CTS_STORE_PORT: {{ template "forgerock.framPort" (list "cts" .) }}
  FRAM_CTS_STORE_SSL: {{ template "forgerock.framSSL" (list "cts" .) }}
  FRAM_CTS_STORE_ROOT_SUFFIX: {{ .Values.fram.stores.ctsStore.rootSuffix }}
  {{- end }}
  {{- if .Values.fram.init.env }}
  {{- with .Values.fram.init.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}