apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forgerock.fullname". }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: fram
    {{- with .Values.fram.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  jksPassword: {{ .Values.fram.keystore.password | b64enc }}