{{- if .Values.frim.useKeystore -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "forgerock.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "forgerock.fullname". }}
    chart: {{ template "forgerock.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: genjks
        image: darkedges/genjks:1.0.0
        imagePullPolicy: {{ .Values.frim.image.imagePullPolicy }}
        command:
          - /usr/bin/genjks.sh
          - {{ template "forgerock.fullname" . }}    
          - frim
        volumeMounts:
          - mountPath: /var/run/secrets/frim
            name: {{ template "forgerock.fullname" . }}-internal-tls  
      restartPolicy: Never
      serviceAccountName: {{ template "forgerock.serviceAccountName" . }}-genjks
      volumes:
        - name: {{ template "forgerock.fullname" . }}-internal-tls
          secret:
            secretName: {{ template "forgerock.fullname" . }}-internal-tls
  backoffLimit: 4
{{- end }}