apiVersion: v1
kind: Secret
metadata:
  name: {{ template "forgerock.fullname". }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frim
    {{- with .Values.frim.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

type: Opaque
data:
  jksPassword: {{ .Values.frim.keystore.password | b64enc }}
  DARKEDGES_REPO_PASSWORD: {{ .Values.frim.secrets.repo.password | b64enc }}
  DARKEDGES_PROVISIONER_LDAP_USERSTORE_PASSWORD: {{ .Values.frim.secrets.provisioner.ldap.userStore.password | b64enc }}