{{- if and (.Values.frim.rbac.enabled) (.Values.frim.useKeystore) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frim
    {{- with .Values.frim.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.frim.serviceAccount.annotations }}
  annotations:
  {{ toYaml .Values.frim.serviceAccount.annotations | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.frim.serviceAccount.automountServiceAccountToken }}
{{- end }}