{{- if and (.Values.frim.rbac.enabled) (.Values.frim.useKeystore) -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.serviceAccountName" . }}-genjks-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frim
    {{- with .Values.frim.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch", "watch", "list"]
{{- end }}