-- hr.000010.view_employees.sql
CREATE OR REPLACE EDITIONING VIEW relationships AS
    SELECT ID, OBJECTTYPES_ID,REV,FULLOBJECT,FIRSTRESOURCECOLLECTION,FIRSTRESOURCEID,FIRSTPROPERTYNAME,SECONDRESOURCECOLLECTION,SECONDRESOURCEID,SECONDPROPERTYNAME,PROPERTIES FROM relationships$0;
