{{- if .Values.frds.proxy.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "forgerock.frds.fullname". }}-schema-claim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.frds.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
{{- end }}