apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.frds.fullname". }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.frds.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.frds.configAnnotations }}
  annotations: {{ toYaml .Values.frds.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- if ne .Values.frds.instance.type "development" }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.bootstrap" (list "replication" 2) }}
  {{- else }}
  {{- if gt .Values.frds.replicaCount 1.0 }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.bootstrap" (list "development" .Values.frds.replicaCount) }}
  {{- end }}
  {{- end }}
  {{- with .Values.frds.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}