apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.frds.fullname". }}-init-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.frds.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.frds.configAnnotations }}
  annotations: {{ toYaml .Values.frds.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.frds.init.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if has .Values.frds.instance.type (list "amconfig" "development") }}
  AMCONFIG_BASE_DN: {{ .Values.frds.profiles.amconfig.baseDn }}
  AMCONFIG_BACKEND_NAME: {{ .Values.frds.profiles.amconfig.backendName }}
  {{- end }}
  {{- if has .Values.frds.instance.type (list "identity" "development") }}
  AMIDENTITYSTORE_BASE_DN: {{ .Values.frds.profiles.identity.baseDn }}
  AMIDENTITYSTORE_BACKEND_NAME: {{ .Values.frds.profiles.identity.backendName }}
  {{- end }}
  {{- if has .Values.frds.instance.type (list "cts" "development") }}
  AMCTS_BASE_DN: {{ .Values.frds.profiles.cts.baseDn }}
  AMCTS_BACKEND_NAME: {{ .Values.frds.profiles.cts.backendName }}
  AMCTS_BACKEND_TOKEN_EXPIRARTION_POLICY: {{ .Values.frds.profiles.cts.tokenExpirationPolicy }}
  {{- end }}
  {{- if has .Values.frds.instance.type (list "idm" "development") }}
  IDM_DOMAIN: {{ .Values.frds.profiles.idm.domain }}
  IDM_BACKEND_NAME: {{ .Values.frds.profiles.idm.backendName }}
  {{- end }}
  INIT_INSTANCE_PROFILE: {{ .Values.frds.instance.type }}
  {{- if ne .Values.frds.instance.type "directory" }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.bootstrap" (list "replication" 2) }}
  {{- else }}
  {{- if gt .Values.frds.replicaCount 1.0 }}
  DS_BOOTSTRAP_REPLICATION_SERVERS: {{ include  "frds.bootstrap" (list "directory" .) }}
  {{- end }}
  {{- end }}