apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "forgerock.frds.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "forgerock.frds.fullname". }}
    {{- with .Values.frds.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podManagementPolicy: {{ .Values.frds.podManagementPolicy }} 
  selector:
    matchLabels:
      {{- include "forgerock.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "forgerock.frds.fullname". }}
  {{- if not .Values.frds.autoscaling.enabled }}
  replicas: {{ .Values.frds.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.frds.updateStrategy }}
  strategy:
    {{ toYaml .Values.frds.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.frds.minReadySeconds }}
  serviceName: {{ template "forgerock.frds.fullname". }}
  template:
    metadata:
      labels:
        {{- include "forgerock.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "forgerock.frds.fullname". }}
        {{- with .Values.frds.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.frds.podLabels }}
        {{- toYaml .Values.frds.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frds-configmap-container.yaml") . | sha256sum }}
       {{- if .Values.frds.podAnnotations }}
      {{- range $key, $value := .Values.frds.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      {{- if .Values.frds.dnsConfig }}
      dnsConfig: {{ toYaml .Values.frds.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.hostname }}
      hostname: {{ toYaml .Values.frds.hostname | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.frds.dnsPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.priorityClassName }}
      priorityClassName: {{ .Values.frds.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.frds.hostNetwork }}
      hostNetwork: {{ .Values.frds.hostNetwork }}
      {{- end }}
      {{- if .Values.frds.nodeSelector }}
      nodeSelector: {{ toYaml .Values.frds.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.tolerations }}
      tolerations: {{ toYaml .Values.frds.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.affinity }}
      affinity: {{ toYaml .Values.frds.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.frds.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if or .Values.frds.podSecurityContext .Values.frds.sysctls }}
      securityContext:
      {{- end }}
      {{- if .Values.frds.podSecurityContext }}
        {{- toYaml .Values.frds.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.frds.sysctls }}
        sysctls:
      {{- range $sysctl, $value := .Values.frds.sysctls }}
        - name: {{ $sysctl | quote }}
          value: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.frds.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.frds.shareProcessNamespace }}
      {{- end }}
      serviceAccountName: {{ template "forgerock.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.frds.terminationGracePeriodSeconds }}
      subdomain: {{ .Values.frds.instance.type }}
      initContainers:
      - name: wait-for-first
        image: opsfleet/depends-on
        imagePullPolicy: {{ .Values.frds.image.imagePullPolicy }}
        {{ template "forgerock.waitfor". }}
      - name: init
        image: {{ .Values.frds.image.repository }}:{{ .Values.frds.image.tag }}
        imagePullPolicy: {{ .Values.frds.image.imagePullPolicy }}
        envFrom:
        - secretRef:
            name: {{ template "forgerock.frds.fullname". }}-secrets
        - configMapRef:
            name: {{ template "forgerock.frds.fullname". }}-init-config
        command:
          - ./docker-entrypoint.sh
          - init
        volumeMounts:
          - mountPath: /opt/frds/instance/data
            name: {{ template "forgerock.frds.fullname". }}-data-volume
        {{- if .Values.frds.useKeystore }}
          - mountPath: /var/run/secrets/frds
            name: {{ template "forgerock.frds.fullname". }}-keystore
            readOnly: true 
        {{- end }}
      containers:
      - name: frds
        image: {{ .Values.frds.image.repository }}:{{ .Values.frds.image.tag }}
        imagePullPolicy: {{ .Values.frds.image.imagePullPolicy }}
        {{- if .Values.frds.lifecycle }}
        lifecycle: {{ toYaml .Values.frds.lifecycle | nindent 12 }}
        {{- end }}
        securityContext: {{ include "frds.containerSecurityContext" . | nindent 12 }}
        env:
        - name: DS_ADVERTISED_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DS_SERVER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if .Values.frds.env }}
        envFrom:
        - configMapRef:
            name: {{ template "forgerock.frds.fullname". }}-config
        {{- end}}
        ports:
        - containerPort: 4444
        {{- if eq .Values.frds.instance.type "replication" }}
        - containerPort: 8989
        {{- else }}
        - containerPort: 1389
        - containerPort: 1636
        - containerPort: 8443
        {{- end }}
        volumeMounts:
          - mountPath: /opt/frds/instance/data
            name: {{ template "forgerock.frds.fullname". }}-data-volume
          {{- if .Values.frds.proxy.enabled }}
          - mountPath: "/schema"
            name: frds-schema-storage
          {{- end }}
          {{- if .Values.frds.useKeystore }}
          - mountPath: /var/run/secrets/frds
            name: {{ template "forgerock.frds.fullname". }}-keystore
            readOnly: true
          {{- end }}
        {{- if .Values.frds.startupProbe }}
        startupProbe: {{ toYaml .Values.frds.startupProbe | nindent 12 }}
        {{- end }}
        livenessProbe: {{ toYaml .Values.frds.livenessProbe | nindent 12 }}
        readinessProbe: {{ toYaml .Values.frds.readinessProbe | nindent 12 }}
        {{- if .Values.frds.resources }}
        resources: {{ toYaml .Values.frds.resources | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.frds.proxy.enabled }}
        - name: frds-schema-storage
          persistentVolumeClaim:
            claimName: frdsschemaclaim
        {{- end }}
        {{- if .Values.frds.useKeystore }}
        - name: {{ template "forgerock.frds.fullname" . }}-keystore
          secret:
            secretName: {{ template "forgerock.frds.fullname" . }}-keystore
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "forgerock.frds.fullname". }}-data-volume
    spec:
      {{- if .Values.frds.volumeClaimTemplates.data.storageClassName }}
      storageClassName: {{ .Values.frds.volumeClaimTemplates.data.storageClassName }}
      {{- end }}
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.frds.volumeClaimTemplates.data.storageSize }}