{{- if .Values.frds.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.frds.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frds
    {{- with .Values.frds.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]
{{- end }}