{{- if .Values.frig.autoscaling.enabled -}}
{{- if not .Values.frig.keda.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  {{- with .Values.frig.autoscaling.annotations }}
  {{- toYaml . | trimSuffix "\n" | nindent 4 }}
  {{- end }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "forgerock.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "forgerock.fullname" . }}
  minReplicas: {{ .Values.frig.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frig.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.frig.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.frig.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.frig.autoscalingTemplate }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.frig.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
