{{- if .Values.frig.keda.enabled -}}
# https://keda.sh/docs/

apiVersion: {{ .Values.frig.keda.apiVersion }}
kind: ScaledObject
metadata:
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "forgerock.fullname" . }}
  {{- if .Values.frig.keda.scaledObject.annotations }}
  annotations: {{ toYaml .Values.frig.keda.scaledObject.annotations | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
{{- if eq .Values.frig.keda.apiVersion "keda.k8s.io/v1alpha1" }}
    deploymentName: {{ include "forgerock.fullname" . }}
{{- else if eq .Values.frig.keda.apiVersion "keda.sh/v1alpha1" }}
    name: {{ include "forgerock.fullname" . }}
{{- end }}
  pollingInterval: {{ .Values.frig.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.frig.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.frig.keda.minReplicas }}
  maxReplicaCount: {{ .Values.frig.keda.maxReplicas }}
  triggers:
{{- with .Values.frig.keda.triggers }}
{{ toYaml . | indent 2 }}
{{ end }}
  advanced:
    restoreToOriginalReplicaCount: {{ .Values.frig.keda.restoreToOriginalReplicaCount }}
{{- if .Values.frig.keda.behavior }}
    horizontalPodAutoscalerConfig:
      behavior:
{{ with .Values.frig.keda.behavior -}}
{{ toYaml . | indent 8 }}
{{ end }}

{{- end }}
{{- end }}