{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "forgerock.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name:  {{ template "forgerock.fullname". }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "forgerock.fullname". }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}