{{- if and .Values.podSecurityPolicy.enabled (empty .Values.frig.existingPsp) -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "forgerock.fullname" . }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  allowedCapabilities:
    - NET_BIND_SERVICE
  {{- if .Values.frig.image.chroot }}
    - SYS_CHROOT
  {{- end }}
{{- if .Values.frig.sysctls }}
  allowedUnsafeSysctls:
  {{- range $sysctl, $value := .Values.frig.sysctls }}
  - {{ $sysctl }}
  {{- end }}
{{- end }}
  privileged: false
  allowPrivilegeEscalation: true
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    #- 'projected'
    - 'secret'
    #- 'downwardAPI'
{{- if .Values.frig.hostNetwork }}
  hostNetwork: {{ .Values.frig.hostNetwork }}
{{- end }}
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  seLinux:
    rule: 'RunAsAny'
{{- end }}