{{- if .Values.frig.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "forgerock.fullname" . }}-keystore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  secretName: {{ template "forgerock.fullname" . }}-keystore
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: localhost
  dnsNames:
  - localhost
  - "*.{{ template "forgerock.fullname". }}-lb"
  - "*.{{ template "forgerock.fullname". }}-lb.{{ .Release.Namespace }}"
  - "*.{{ template "forgerock.fullname". }}-lb.{{ .Release.Namespace }}.svc"
  - "*.{{ template "forgerock.fullname". }}-lb.{{ .Release.Namespace }}.svc.cluster.local"
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: jksPassword
        name: {{ template "forgerock.fullname". }}-secrets
{{- end }}