{{- if .Values.frig.useKeystore -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "forgerock.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-5"
spec:
  template:
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: genjks
        image: {{ .Values.genjks.image.repository }}:{{ .Values.genjks.image.tag }}
        imagePullPolicy: {{ .Values.genjks.image.imagePullPolicy }}
        command:
          - /genjks.sh
          - {{ template "forgerock.fullname" . }}      
          - frig
        env:
        - name: VAULT_ISSUER
          value: darkedges
        volumeMounts:
          - mountPath: /var/run/secrets/frig
            name: {{ template "forgerock.fullname" . }}-internal-tls  
      restartPolicy: Never
      serviceAccountName: {{ template "forgerock.serviceAccountName" . }}-genjks
      volumes:
        - name: {{ template "forgerock.fullname" . }}-internal-tls
          secret:
            secretName: {{ template "forgerock.fullname" . }}-internal-tls
  backoffLimit: 4
{{- end }}