apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "forgerock.fullname". }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.frig.configAnnotations }}
  annotations: {{ toYaml .Values.frig.configAnnotations | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.frig.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}