apiVersion: v1
kind: Service
metadata:
  name: {{ template "forgerock.fullname". }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{ include "forgerock.selectorLabels" . | nindent 6 }}
  ports:
    - name: tcp-{{ lower .Values.frig.ingress.backend.protocol }}
      port: {{ .Values.frig.ingress.backend.port}}
      targetPort: {{ .Values.frig.ingress.backend.port}}
{{- if .Values.isStatefulSet }}
---
apiVersion: v1
kind: Service
metadata:
  name: frig
  namespace: {{ .Release.Namespace }}
  labels:
    app: frig
    chart: {{ template "forgerock.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: {{ template "forgerock.fullname". }}
  ports:
    - name: tcp-{{ lower .Values.frig.ingress.backend.protocol }}
      port: {{ .Values.frig.ingress.backend.port}}
{{- end }}