apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "forgerock.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "forgerock.labels" . | nindent 4 }}
    app.kubernetes.io/component: frig
    {{- with .Values.frig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "forgerock.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frig
  {{- if not .Values.frig.autoscaling.enabled }}
  replicas: {{ .Values.frig.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.frig.updateStrategy }}
  strategy:
    {{ toYaml .Values.frig.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.frig.minReadySeconds }}
  template:
    metadata:
      labels:
        {{- include "forgerock.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frig
        {{- with .Values.frig.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.frig.podLabels }}
        {{- toYaml .Values.frig.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frig-configmap.yaml") . | sha256sum }}
       {{- if .Values.frig.podAnnotations }}
      {{- range $key, $value := .Values.frig.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    spec:
      {{- if .Values.frig.dnsConfig }}
      dnsConfig: {{ toYaml .Values.frig.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.hostname }}
      hostname: {{ toYaml .Values.frig.hostname | nindent 8 }}
      {{- end }}
      dnsPolicy: {{ .Values.frig.dnsPolicy }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.priorityClassName }}
      priorityClassName: {{ .Values.frig.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.frig.hostNetwork }}
      hostNetwork: {{ .Values.frig.hostNetwork }}
      {{- end }}
      {{- if .Values.frig.nodeSelector }}
      nodeSelector: {{ toYaml .Values.frig.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.tolerations }}
      tolerations: {{ toYaml .Values.frig.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.affinity }}
      affinity: {{ toYaml .Values.frig.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .Values.frig.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if or .Values.frig.podSecurityContext .Values.frig.sysctls }}
      securityContext:
      {{- end }}
      {{- if .Values.frig.podSecurityContext }}
        {{- toYaml .Values.frig.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.frig.sysctls }}
        sysctls:
      {{- range $sysctl, $value := .Values.frig.sysctls }}
        - name: {{ $sysctl | quote }}
          value: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.frig.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.frig.shareProcessNamespace }}
      {{- end }}
      serviceAccountName: {{ template "forgerock.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.frig.terminationGracePeriodSeconds }}
      initContainers:
        - name: init
          image: {{ .Values.frig.image.repository }}:{{ .Values.frig.image.tag }}
          imagePullPolicy: {{ .Values.frig.image.imagePullPolicy }}
          command:
            - ./docker-entrypoint.sh
            - init
          volumeMounts:
            {{- if .Values.frig.certificate.enabled }}
            - name: keystores
              mountPath: "/var/frig/secrets"
              readOnly: true  
            {{- end}}
      containers:
      - name: frig
        image: {{ .Values.frig.image.repository }}:{{ .Values.frig.image.tag }}
        imagePullPolicy: {{ .Values.frig.image.imagePullPolicy }}
        {{- if .Values.frig.lifecycle }}
        lifecycle: {{ toYaml .Values.frig.lifecycle | nindent 12 }}
        {{- end }}
        securityContext: {{ include "frig.containerSecurityContext" . | nindent 12 }}
        env:
          {{- if .Values.frig.certificate.enabled }}
          - name: IG_KEYSTORE_DIRECTORY
            value: /var/frig/secrets
          - name: IG_KEYSTORE_ALIAS
            value: certificate
          - name: IG_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "forgerock.fullname" . }}-secrets
                key: jksPassword
          {{- end }}
        {{- if .Values.frig.env }}
        envFrom:
          - configMapRef:
              name: {{ template "forgerock.fullname". }}-config
        {{- end }}   
        volumeMounts:
          {{- if .Values.frig.certificate.enabled }}
          - name: keystores
            mountPath: "/var/frig/secrets"
            readOnly: true  
          {{- end }}
        ports:
        {{- if .Values.frig.certificate.enabled }}
        - containerPort: 8443
        {{- else }}
        - containerPort: 8080
        {{- end }}
        {{- if .Values.frig.startupProbe }}
        startupProbe: {{ toYaml .Values.frig.startupProbe | nindent 12 }}
        {{- end }}
        livenessProbe: {{ toYaml .Values.frig.livenessProbe | nindent 12 }}
        readinessProbe: {{ toYaml .Values.frig.readinessProbe | nindent 12 }}
        {{- if .Values.frig.resources }}
        resources: {{ toYaml .Values.frig.resources | nindent 12 }}
        {{- end }}
      volumes:
        {{- if .Values.frig.certificate.enabled }}
        - name: keystores
          secret:
            secretName: {{ template "forgerock.fullname" . }}-keystore
        {{- end }}